from flask import current_app


def query_llm(prompt: str) -> str:
    """
    Handles interaction with a language model.

    :param prompt: Sanitized user prompt
    :return: Response generated by the LLM
    """
    try:
        current_app.logger.info(f"[LLM] Prompt: {prompt}")

        # Simulated LLM response (placeholder)
        response = f"LLM Response to: {prompt}"

        current_app.logger.info(f"[LLM] Response: {response}")
        return response

    except Exception as e:
        current_app.logger.exception("LLM call failed.")
        raise RuntimeError("Failed to get response from LLM") from e
